kind = "DojoModel"
class_hash = "0x1e8e29d26c9e24f36ecb4f4e29b52bb108dad4158077824308e12f25795dca0"
original_class_hash = "0x1e8e29d26c9e24f36ecb4f4e29b52bb108dad4158077824308e12f25795dca0"
abi = "manifests/slot/abis/base/models/zkrown_models_index_tile.json"
name = "zkrown::models::index::tile"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "id"
type = "u8"
key = true

[[members]]
name = "army"
type = "u32"
key = false

[[members]]
name = "owner"
type = "u32"
key = false

[[members]]
name = "dispatched"
type = "u32"
key = false

[[members]]
name = "to"
type = "u8"
key = false

[[members]]
name = "from"
type = "u8"
key = false

[[members]]
name = "order"
type = "felt252"
key = false
