[book]
authors = ["Z-Labs"]
language = "en"
multilingual = false
src = "src"
title = "zConqueror Book"

[output.html]
git-repository-url = "https://github.com/z-korp/zconqueror-contracts/"
edit-url-template = "https://github.com/z-korp/zconqueror-contracts/book/{path}"

[output.html.playground]
runnable = false