kind = "DojoContract"
class_hash = "0x5d0b65b7d2524f498f0bbeb6635947856644695e6e774abbb6a50784f468c2b"
original_class_hash = "0x5d0b65b7d2524f498f0bbeb6635947856644695e6e774abbb6a50784f468c2b"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/zkrown_systems_play_play.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "zkrown::systems::play::play"
