kind = "DojoContract"
class_hash = "0x498ac6f20841222e5ed6c741518e2583ae59eb7745c0ce3fcaaea087670aba8"
original_class_hash = "0x498ac6f20841222e5ed6c741518e2583ae59eb7745c0ce3fcaaea087670aba8"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/zkrown_systems_play_play.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "zkrown::systems::play::play"
